### ISSUE TITLE
formatting

### ISSUE THREAD

**Issue by cristeigabriel** [NukoOoOoOoO/winter-linux#1]
please fix the current formatting its horrible

**Comment by cristeigabriel** [comment]
also you can relink 'xemacs' to this github account

**Comment by NukoOoOoOoO** [comment]
Hey please check [format branch](https://github.com/NukoOoOoOoO/winter-linux/tree/format), let me know if there is any improvement can be made

**Comment by NukoOoOoOoO** [comment]
I think it is good now
