### ISSUE TITLE
Won't compile for some reason

### ISSUE THREAD

**Issue by mixifav118** [NukoOoOoOoO/winter-linux#2]
When running "./tool.sh -b -l" I get these errors. I can't seem to figure out whats wrong.

In file included from /home/user/winter-linux/src/hooks/hooks.cpp:2:
/home/user/winter-linux/src/hooks/hooks.h: In member function 'bool c_detour::create(void*, void*)':
/home/user/winter-linux/src/hooks/hooks.h:58:31: error: '_SC_PAGE_SIZE' was not declared in this scope

   58 |         m_page_size = sysconf(_SC_PAGE_SIZE);
      |                               ^~~~~~~~~~~~~
/home/user/winter-linux/src/hooks/hooks.h:58:23: error: 'sysconf' was not declared in this scope; did you mean 'swscanf'?
   58 |         m_page_size = sysconf(_SC_PAGE_SIZE);
      |                       ^~~~~~~
      |                       swscanf
[ 42%] Building CXX object CMakeFiles/winter.dir/src/sdk/interfaces.cpp.o
/home/user/winter-linux/src/hooks/hooks.cpp: In function 'int hook_funcs::get_whitelist_spew_flags::hook(void*)':
/home/user/winter-linux/src/hooks/hooks.cpp:141:42: warning: unused parameter 'ptr' [-Wunused-parameter]
  141 | int get_whitelist_spew_flags::hook(void* ptr)
      |                                    ~~~~~~^~~
[ 46%] Building CXX object CMakeFiles/winter.dir/src/sdk/netvars.cpp.o
make[2]: *** [CMakeFiles/winter.dir/build.make:90: CMakeFiles/winter.dir/src/features/chams.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/winter.dir/build.make:160: CMakeFiles/winter.dir/src/hooks/hooks.cpp.o] Error 1
In file included from /home/user/winter-linux/src/main.cpp:2:
/home/user/winter-linux/src/hooks/hooks.h: In constructor 'c_detour::c_detour(void*, void*)':
/home/user/winter-linux/src/hooks/hooks.h:30:31: error: '_SC_PAGE_SIZE' was not declared in this scope
   30 |         m_page_size = sysconf(_SC_PAGE_SIZE);
      |                               ^~~~~~~~~~~~~
/home/user/winter-linux/src/hooks/hooks.h:30:23: error: 'sysconf' was not declared in this scope; did you mean 'swscanf'?
   30 |         m_page_size = sysconf(_SC_PAGE_SIZE);
      |                       ^~~~~~~
      |                       swscanf
In file included from /home/user/winter-linux/src/main.cpp:2:
/home/user/winter-linux/src/hooks/hooks.h: In member function 'bool c_detour::create(void*, void*)':
/home/user/winter-linux/src/hooks/hooks.h:58:31: error: '_SC_PAGE_SIZE' was not declared in this scope
   58 |         m_page_size = sysconf(_SC_PAGE_SIZE);
      |                               ^~~~~~~~~~~~~
/home/user/winter-linux/src/hooks/hooks.h:58:23: error: 'sysconf' was not declared in this scope; did you mean 'swscanf'?
   58 |         m_page_size = sysconf(_SC_PAGE_SIZE);
      |                       ^~~~~~~
      |                       swscanf
make[2]: *** [CMakeFiles/winter.dir/build.make:258: CMakeFiles/winter.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/winter.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Loading cheat...
cp: cannot stat 'cmake-build-release/libwinter.so': No such file or directory
Successfully injected!

**Comment by NukoOoOoOoO** [comment]
I have no idea why it can compile for me, can you try adding ``#include <unistd.h>`` at the beginning of ``hooks.h``?

**Comment by mixifav118** [comment]
Yeah that fixed it. Thank you!
