### ISSUE TITLE
doesnt inject

### ISSUE THREAD

**Issue by toxic-user** [NukoOoOoOoO/winter-linux#4]
last 2 lines of log:
[16:57:40] [-] The address of load_from_buffer is invalid.
[16:57:40] [!] Address

**Comment by toxic-user** [comment]
[16:57:40] [-] The address of load_from_buffer is invalid.
[16:57:40] [!] Address

**Comment by NukoOoOoOoO** [comment]
That means the signature is outdated, [I wrote about how to update the signature](https://github.com/NukoOoOoOoO/winter-linux/blob/dev/src/sdk/signatures.cpp#L9-L35), or you just use non-aligned pattern scanning method, which is slower but you dont have to update the signatures every time when the game has an update
